test openclient docker

diff --git a/.github/workflows/test-docker.yml b/.github/workflows/test-docker.yml
--- a/.github/workflows/test-docker.yml
+++ b/.github/workflows/test-docker.yml
@@ -50,7 +50,7 @@ jobs:
               apt-get update && apt-get install -y python3 python3-pip
               pip3 install requests
               echo 'Testing write to Onedata...'
-              echo 'hello world' > /mnt/onedata/debug-write.txt || echo 'Write failed'
+              echo 'hello world' > /mnt/onedata/GTN\ data/debug-write.txt || echo 'Write failed'
               ls -lah /mnt/onedata || true
               echo 'Running test download...'
               python3 bin/test-download.py
